### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by jkwatson** [ggalmazor/jfry#10]
I would love to use jfry in a new project!  Would be immensely helpful if it were in maven central (or any other public repository).

**Comment by ggalmazor** [comment]
That's great! 

Please bear in mind that JFry is still too experimental to be used in production and is ought to change a lot before considering to be stable.

I've just filled a ticket for the creation of a repository in OSSRH to be able to publish it into maven central. Will let you know when this happens.

All your feedback will be more than welcome and will be decisive in the future design of JFry :)

**Comment by ribomation** [comment]
I can recommend jcentral as an alternative to Maven Central.
https://bintray.com/bintray/jcenter
I have used it myself, and it's easy to set up and get going.

**Comment by ggalmazor** [comment]
Thx for the tip @ribomation 

Can we have it in both repos or is it mutually exclusive?

**Comment by jitpack-io** [comment]
Hi all
Perhaps in the meantime you can fetch JFry as maven dependency from JitPack https://jitpack.io/#ggalmazor/jfry/a7d1ae2cf8 
A GitHub release would make a nice version too.

**Comment by ggalmazor** [comment]
Great! I'll manage all this through the weekend. Now i'm deploying in Bintray...

**Comment by ribomation** [comment]
@ggalmazor 
You can publish to both. It's a matter of which repo the user has defined in the build script. You swap mavenCentral() for jcenter() in the repositories closure of build.gradle.
https://docs.gradle.org/current/userguide/dependency_management.html#sub:maven_jcenter

**Comment by ggalmazor** [comment]
Allright. Is this something that's good to have or if we manage to get the jars on maven central is enough?

**Comment by ggalmazor** [comment]
Hmmm this is more difficult than I thought... Will try to publish something through the weekend...

**Comment by ribomation** [comment]
You can manually upload to jcenter, which might help initially. Deploying to mvn central is on the other hand a long tedious process before it's in place.

**Comment by ggalmazor** [comment]
Alright! We have https://jitpack.io/#ggalmazor/jfry/0.0.10 ready for you guys

**Comment by ggalmazor** [comment]
Ok, I've just released 0.0.15 in maven central.
To be honest, jcenter() is probing to be hard for me right now for whatever reason... I guess that maven central will have to be enough for now.

I'm also trying to figure out the best workflow for integrating with travis. I am sure that we're going to use semantic versioning and I don't think that snapshots would fit well in it... I think that we could have some kind of sequential canary versions deployed through jitpack.io by automatic build tagging.

Anyway... one step at a time.

Now I'd want to ask you a big favor to all of you who decide to use jfry: please open issues, send feedback, open gitter chats with me... whatever you feel like doing because this library needs real experience of people using it to improve and evolve.

I have no doubt that jfry will change (improve) dramatically in a very short time. There are lots of things that need to receive some love: request (params, body, multipart) handling, jetty (or any other server for that matter) integration, streaming operation, etc.

Also a big thanks to everyone for pushing me to publish jfry ;)
